version: '3'
services:
  nexus3:
    restart: always
    image: 'sonatype/nexus3'
    hostname: 'nexus3'
    container_name: nexus3
    ports:
      - '8081:8081'
    volumes:
      - '~/nexus-data:/nexus-data'
