version: '3'
services:
  teamcity-server:
    restart: always
    image: 'jetbrains/teamcity-server'
    hostname: 'teamcity-server'
    container_name: teamcity-server
    ports:
      - '8888:8111'
    volumes:
      - '~/dockerData/teamcity-data:/data/teamcity_server/datadir'
      - '~/dockerData/teamcity-logs:/opt/teamcity/logs'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      TEAMCITY_SERVER_MEM_OPTS: "-Xmx2g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"