version: '2' 
services: 
 jenkins:
   build: .
   restart: always
   privileged: true
   image: registry.vcredit.com/o2o/jenkins
  # volumes:
  # - /home/o2ouser/dockerData/o2o-jenkins:/var/jenkins_home
   ports:
   - 8282:8080
   - 50000:50000
   container_name: o2o-jenkins
   mem_limit: 2g
