version: '3'
services:
  jenkins-blueocean:
    restart: always
    image: 'jenkinsci/blueocean'
    hostname: 'jenkins'
    container_name: jenkins
    ports:
      - '8080:8080'
    volumes:
      - '~/dockerData/jenkins-data:/var/jenkins_home'
      - '~:/home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    user: root
