version: '3'
services:
  iot-nginx:
    restart: always
    image: nginx:1.25.1
    container_name: iot-nginx
    environment:
      - TZ="Asia/Shanghai"
    ports:
      - '880:880'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx