version: '2'
services:
 mysql:
   restart: always
   build: .
   image: mysql:5.7.19
   volumes:
   - /data/dockerData/mysql/data:/var/lib/mysql
   - /etc/localtime:/etc/localtime
   environment:
    MYSQL_ROOT_PASSWORD: vcredit_o2o(Mysql)
    --character-set-server: utf8mb4
   ports:
   - 3308:3306
   container_name: mysql
   mem_limit: 8g
