version: '2'
services:
 mysql:
   restart: always
   build: .
   image: mysql:5.7.24
   volumes:
   - /data/dockerData/mysql/data:/var/lib/mysql
   - /etc/localtime:/etc/localtime
   command: [--character-set-server=utf8mb4,--collation-server=utf8mb4_unicode_ci]
   environment:
    MYSQL_ROOT_PASSWORD: 123456
   ports:
   - 3308:3306
   container_name: mysql
   mem_limit: 8g
