version: '2'
services:
 mysql:
   restart: always
   build: .
   image: registry.cn-hangzhou.aliyuncs.com/ags/mysql-ags:5.7.40
   volumes:
   - ~/dockerData/mysql/data:/var/lib/mysql
   - /etc/timezone:/etc/timezone
   - /etc/localtime:/etc/localtime
   command: [--character-set-server=utf8mb4,--collation-server=utf8mb4_unicode_ci]
   environment:
    MYSQL_ROOT_PASSWORD: qJni1026CiyBUTVy
   ports:
   - 3308:3306
   container_name: mysql
   mem_limit: 2g
