version: '2'
services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio@@123
      - MINIO_DEFAULT_BUCKETS=iot-bucket-1:policy,iot-bucket-2
    volumes:
      - ~/minioData:/data