version: '3.1'
services:
  pg-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD:pgsql@@123
      - PGDATA:/var/lib/postgresql/data/pgdata
    volumes:
      - ~/pgmount:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pg-adminer:
    image: adminer
    restart: always
    ports:
      - "8180:8080"