version: '2'
services:
 redis:
   restart: always
   build: .
   image: evan1120/redis
   volumes:
   - ~/dockerData/redis/data:/data
   - /etc/timezone:/etc/timezone
   - /etc/localtime:/etc/localtime
   ports:
   - 6379:6379
   container_name: redis
   mem_limit: 2g